'''
    Add a function called summary() in coin module from exercise 107.
    This function shows some information generated by the functions the package already contains.
'''
import coin

number = float(input('Choose a price: R$ '))
coin.summary(number, 10, 35)
